### ISSUE TITLE
Add Docker Each Service

### ISSUE THREAD

**Issue by wcorn** [Garamgaebee/BE#18]
## Description
각 서비스 도커 파일 추가

## To-Do
- [x] add docker image service 
- [x] add docker eureka server 
- [x] add docker auth service 
- [x] add docker member service 
- [x] add docker thread service 

## ETC
기타사항
