### ISSUE TITLE
Fix Spring Setting

### ISSUE THREAD

**Issue by seock1000** [Garamgaebee/BE#39]
## Description
docker 적용을 위한 yml 파일 변경

## To-Do
- [x] api gateway yml 파일 수정
- [x] auth service yml 파일 수정
- [x] eureka server yml 파일 수정

## ETC
기타사항
