### ISSUE TITLE
auth-service-api-documentation

### ISSUE THREAD

**Issue by seock1000** [Garamgaebee/BE#59]
## Description
auth-service 스웨거 사용한 api 문서 작성

## To-Do
- [x] 로그인 api
- [x] refresh token으로 토큰 재발급 api
- [x] 로그아웃 api
- [x] 메일 전송 api
- [x] 메일 인증코드 검사 api
- [x] 회원가입 api
- [x] 닉네임 유효성 검사 api
- [x] 회원 탈퇴 api
