### ISSUE TITLE
thread-service-documentation

### ISSUE THREAD

**Issue by seock1000** [Garamgaebee/BE#64]
## Description
thread-service 문서화 및 테스트

## To-Do
- [ ] 개인 스레드 생성 api
- [ ] 팀 스레드 생성 api
- [ ] 스레드 삭제 api
- [ ] 스레드 메인 리스트 조회 api
- [ ] 스레드 팀 리스트 조회 api
- [ ] 개인 프로필로 댓글 생성 api
- [ ] 팀 프로필로 댓글 생성 api
- [ ] 댓글 삭제 api
- [ ] 스레드, 댓글 좋아요 생성 api
- [ ] 스레드, 댓글 좋아요 삭제 api

## ETC
기타사항
