### ISSUE TITLE
member-service-documentation

### ISSUE THREAD

**Issue by seock1000** [Garamgaebee/BE#69]
## Description
member-service 문서화 및 테스트

## To-Do
- [ ] 멤버 조회 API
- [ ] 프로필 이미지 등록 API
- [ ] 프로필 이미지 수정 API
- [ ] 멤버 생성 API(feign)
- [ ] 닉네임 중복 확인 API(feign)
- [ ] 멤버 조회 API(feign)
- [ ] 회원 탈퇴 API(feign)
- [ ] 팀에 속한 회원 리스트 조회 API(feign)
