### ISSUE TITLE
Member API Implementation

### ISSUE THREAD

**Issue by destiny3912** [Garamgaebee/BE#7]
## Description
설명을 작성하세요.

## To-Do
- [ ] 회원 등록 API
- [ ] 회원 조회 API
- [ ] 회원 탈퇴 API
- [ ] 프로필 이미지 등록 API
- [ ] 프로필 이미지 삭제 API
- [ ] 회원 조회 Feign API
- [ ] 회원 닉네임 중복 확인 Feign API

## ETC
모듈 아키텍쳐 수정
