### ISSUE TITLE
notification-service-secret-file-setting

### ISSUE THREAD

**Issue by seock1000** [Garamgaebee/BE#92]
## Description
notification-service 민감정보 처리 및 rds 설정 정보 파일 구성

## To-Do
- [x] notification rds 설정 파일 생성
- [x] rds notification DB 생성
- [x] git cache 제거
